replicaCount: 2

image:
  repository: ""
  tag: petclinic
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: petclinic.local
      paths:
        - path: /
          pathType: Prefix
