apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
