apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
    spec:
      serviceAccountName: traefik
      containers:
        - name: traefik
          image: traefik:v3.0
          args:
            - "--providers.kubernetescrd"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.forwardedHeaders.insecure=true"
            - "--entrypoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0"
            - "--entrypoints.web.proxyProtocol.insecure=true"
            - "--entrypoints.web.proxyProtocol.trustedIPs=0.0.0.0/0"
            - "--accesslog"

          ports:
            - name: web
              containerPort: 80
