apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: hello-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["traefik.io"]
    resources:
      - middlewares
      - ingressroutes
      - tlsstores
      - serverstransports
      - serverstransporttcps
      - ingressroutetcps
      - ingressrouteudps
      - middlewaretcps
      - tlsoptions
      - traefikservices
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-binding
roleRef:
  kind: ClusterRole
  name: traefik-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: hello-ns
